#!/bin/bash

Find_Executables() {
    echo -n "$PATH" | \
    xargs -d ":" -I "{}" \
    find -L "{}" -maxdepth 1 -type f -executable -readable -printf "%f\n"
}

cmd=$(Find_Executables | sort -u | cakemenu)
exec $cmd
